language:
  php

php:
  - '7.1'
  - '7.2'
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.xml --testdox

after_success:
  - travis_retry php vendor/bin/php-coveralls
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
